DROP TABLE Customers;
DROP TABLE DeliveryFactTable;
DROP TABLE Orders;
DROP TABLE Shippings;

CREATE TABLE DeliveryFactTable( 
  RES_ID INT NOT NULL,
  ORDER_ID INT NOT NULL,
  CUST_ID INT NOT NULL,
  PAYTMENT_ID INT NOT NULL,
  ORDER_STATUS varchar(50) NOT NULL,
  ORDER_AMT INT NOT NULL,
  CUST_LOCATION_ID varchar(100) NOT NULL,
  REST_LOCATION_ID varchar(100) NOT NULL
);
