-- Original table https://www.programiz.com/sql/online-compiler/
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Shippings;  

DROP TABLE IF EXISTS DeliveryFactTable;
DROP TABLE IF EXISTS RestaurantDimensionTable ;
DROP TABLE IF EXISTS CustomerDimensionTable;
DROP TABLE IF EXISTS DriverDimensionTable;
DROP TABLE IF EXISTS LocationDimensionTable;
DROP TABLE IF EXISTS OrderDimensionTable;
DROP TABLE IF EXISTS PaymentDimensionTable;

CREATE TABLE DeliveryFactTable( 
  RES_ID INT NOT NULL,
  ORDER_ID INT NOT NULL,
  CUST_ID INT NOT NULL,
  DRIVER_ID INT NOT NULL,
  PAYMENT_ID INT NOT NULL,
  
  ORDER_STATUS varchar(50) NOT NULL,
  ORDER_AMT INT NOT NULL,
  
  DELIVERY_ID INT NOT NULL,
  DELIVERY_QUANTITY INT NOT NULL,
  DELIVERY_REVENUE INT NOT NULL,
  DELIVERY_PICKUPTIME INT NOT NULL,
  DELIVERY_ARRIVALTIME INT NOT NULL,
  
  PRIMARY KEY (DELIVERY_ID),
  FOREIGN KEY (RES_ID) REFERENCES RestaurantDimensionTable(RES_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES OrderDimensionTable(ORDER_ID),
  FOREIGN KEY (CUST_ID) REFERENCES CustomerDimensionTable(CUST_ID),
  FOREIGN KEY (PAYMENT_ID) REFERENCES PaymentDimensionTable(PAYMENT_ID),
  FOREIGN KEY (DRIVER_ID) REFERENCES DriverDimensionTable(DRIVER_ID)
);

CREATE TABLE RestaurantDimensionTable( 
  RES_ID INT NOT NULL,
  RES_NAME varchar(100) NOT NULL,
  RES_TEL varchar(100) NOT NULL,
  RES_CATEGORY varchar(100) NOT NULL,
  
  PRIMARY KEY (RES_ID)
);

CREATE TABLE CustomerDimensionTable( 
  CUST_ID INT NOT NULL,
  CUST_NAME varchar(100) NOT NULL,
  CUST_TEL int NOT NULL,
  CUST_PWORD varchar(100) NOT NULL,
  
  PRIMARY KEY (CUST_ID)
);

CREATE TABLE DriverDimensionTable( 
  DRIVER_ID INT NOT NULL,
  DRIVER_NAME varchar(100) NOT NULL,
  DRIVER_TEL varchar(100) NOT NULL,
  DRIVER_IC_NUM varchar(100) NOT NULL,
  DRIVER_CAR_BRAND varchar(100) NOT NULL,
  DRIVER_CAR_NUMPLATE varchar(100) NOT NULL,
  
  PRIMARY KEY (DRIVER_ID)
);

CREATE TABLE LocationDimensionTable( 
  LOCATION_ID INT NOT NULL,
  STATE varchar(100) NOT NULL,
  CITY varchar(100) NOT NULL,
  ZIP INT NOT NULL,
  STREET varchar(100) NOT NULL,
  
  PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE OrderDimensionTable( 
  ORDER_ID INT NOT NULL,
  ORDER_STATUS varchar(100) NOT NULL,
  ORDER_AMT varchar(100) NOT NULL,
  ORDER_YEAR varchar(100) NOT NULL,
  ORDER_MONTH INT NOT NULL,
  ORDER_DAY INT NOT NULL,
  ORDER_TIME INT NOT NULL,
  
  PRIMARY KEY (ORDER_ID)
);

CREATE TABLE PaymentDimensionTable( 
  PAYMENT_ID INT NOT NULL,
  PROMO_CODE INT NOT NULL,
  PAYMENT_METHOD varchar(100) NOT NULL,
  PAYMENT_AMOUNT INT NOT NULL,
  
  PRIMARY KEY (PAYMENT_ID)
);
